version: '3'

services: 

  app:
    build: 
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node index.js
    networks: 
      - node-network
    volumes: 
      - app-volume:/usr/src/app
    tty: true
    ports: 
      - "3000:3000"
    depends_on: 
       - db
  
  nginx:
    build:
      context: nginx
    container_name: nginx
    working_dir: /var/www/html
    entrypoint: dockerize -template ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf -timeout 20s nginx -g 'daemon off;'
    environment:
      - NGINX_HOST=app
      - NGINX_PORT=3000
    restart: always
    tty: true
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    networks:
      - node-network
    depends_on:
        - app

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network

volumes: 
  app-volume:

networks: 
  node-network:
    driver: bridge     